config/routes.rb
Rails.application.routes.draw do

   devise_for :users
  root to: "homes#top"
  get 'home/about' => "homes#about"
  #ネストさせる
  resources :books do
    resource :favorites, only:[:create, :destroy]
    resources :book_comments, only:[:create, :destroy]
  end
  #ネストさせる
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
     get "search" => "searches#search"
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

#フォローする時
def create
  user = User.find(params[:user_id])
  current_user.follow(user)
  redirect_to request.referer
end

#フォロー外す時
def destroy
  user = User.find(params[:user_id])
  current_user.unfollow(user)
  redirect_to request.referer
end

#フォロー一覧
def followings
  user = User.find(params[:user_id])
  @users = user.followings.page(params[:page])
end

#フォロワー一覧
def followers
  user = User.find(params[:user_id])
  @users = user.followers.page(params[:page])
end

end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_following.html.erb
  <% if current_user.following?(user) %>
    <th>
      <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class:'btn btn-info' %>
    </th>
    <% else %>
    <th>
      <%= link_to 'フォローする', user_relationships_path(user.id), method: :post, class:'btn btn-success' %>
    </th>
  <% end %>

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
  <%= render '/users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
  <%= render '/users/index', users: @users %>
<% else %>
  <p>ユーザーはいません</p>
<% end %>